### ISSUE TITLE
Seekable HTTP stream?

### ISSUE THREAD

**Issue by ngbrown** [mlhpdx/seekable-s3-stream#5]
I use the Minio and their S3 compatible [library](https://github.com/minio/minio-dotnet) so I don't take a reference to the entire S3 library. Also, other HTTP servers support ranges, so a general purpose HTTP client stream seems to be the most useful. It would work against any URL, including S3 servers.

**Comment by lee-11** [comment]
That's true, and there are other such libraries around.￼ This library specifically addresses streams with the S3 API, protected by IAM.￼￼

**Comment by ngbrown** [comment]
@lee-11 do you know of a library that creates a seekable stream against a URL with the standard .NET `HttpClient`?

**Comment by mlhpdx** [comment]
I'm not sure what would best fit your needs, but there are a few here on [Github](https://github.com/search?l=C%23&q=seekable+stream&type=Repositories). Of those, it looks like https://github.com/maxpiva/NutzCode.Libraries.Web is the most full featured (perhaps overly so since this is really a pretty simple problem), but I've not used it.
